$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1527858166266.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d84b9febeb9f4f4bb1bc65b1aa9572e5",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ced1bfcad5c0442783a43a5d0f603a4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.1",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "textShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}},
            "location":{
              "x":60,
              "y":10},
            "size":{
              "width":1191,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"becb1b01fbb1448cb59bf22eedfc6514",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.1",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "textShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}},
                "location":{
                  "x":60,
                  "y":10},
                "size":{
                  "width":1191,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"ba4e85d7482d49afa990fb5dd5a4546c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":113,
              "y":47},
            "size":{
              "width":28,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3960c8e9fa1148b1aba60a0ff62c18d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":47},
                "size":{
                  "width":28,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdca2a2ba01d4d6bb725ba4c45a0c0aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":47},
            "size":{
              "width":268,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"519f6daaa0ab42f7809f40c1eddaae55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":47},
                "size":{
                  "width":268,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d7dc79238f44e2fb0e097468d25ad92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":118},
            "size":{
              "width":957,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"526d061745424f72a5bde4aec26911c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":118},
                "size":{
                  "width":957,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.png"}},
{
          "id":"002407388b4c4e20999ff5cb76a15eae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":121},
            "size":{
              "width":39,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba598652d32d4643ab9edf20bc7c1b7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":121},
                "size":{
                  "width":39,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"687c9df62f1e478caf45e7b111968ad2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":130},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择学期",
                      "target":{
                        "targetType":"page",
                        "url":"选择学期.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"4385970d609e43319ac9faa0d684e64d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":705,
              "y":129},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择课程",
                      "target":{
                        "targetType":"page",
                        "url":"选择课程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"cc5f82157a8c450880cbcbbae8638432",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":790,
              "y":73},
            "size":{
              "width":184,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df97320436f24daaaf402aa46a3e65d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":790,
                  "y":73},
                "size":{
                  "width":184,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8f35e7cd1e64fa7a0da95b3313e05b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":980,
              "y":73},
            "size":{
              "width":80,
              "height":23},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e7919945b4f485ead0923cdbbe4561f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":980,
                  "y":73},
                "size":{
                  "width":80,
                  "height":23},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"fcf2a8759c7941c3bc98bddb02d0d7a8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":129},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 进行选课",
                      "target":{
                        "targetType":"page",
                        "url":"进行选课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"bb751a39178141b9a28fed9a8e117427",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":129},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1<br> (If 选中项值 当前部件 = &quot;修改密码&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"修改密码",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2<br> (Else If 选中项值 当前部件 = &quot;查看个人信息&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"查看个人信息",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"查看个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 3<br> (Else If 选中项值 当前部件 = &quot;修改个人信息&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"修改个人信息",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"修改个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"a8d8f4520ea74206b0bac8cb91fb49b0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":383,
              "y":130},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择课程",
                      "target":{
                        "targetType":"page",
                        "url":"选择课程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}}]}},
  "masters":{
},
  "objectPaths":{
    "ced1bfcad5c0442783a43a5d0f603a4b":{
      "scriptId":"u0"},
    "becb1b01fbb1448cb59bf22eedfc6514":{
      "scriptId":"u1"},
    "ba4e85d7482d49afa990fb5dd5a4546c":{
      "scriptId":"u2"},
    "3960c8e9fa1148b1aba60a0ff62c18d7":{
      "scriptId":"u3"},
    "cdca2a2ba01d4d6bb725ba4c45a0c0aa":{
      "scriptId":"u4"},
    "519f6daaa0ab42f7809f40c1eddaae55":{
      "scriptId":"u5"},
    "8d7dc79238f44e2fb0e097468d25ad92":{
      "scriptId":"u6"},
    "526d061745424f72a5bde4aec26911c6":{
      "scriptId":"u7"},
    "002407388b4c4e20999ff5cb76a15eae":{
      "scriptId":"u8"},
    "ba598652d32d4643ab9edf20bc7c1b7d":{
      "scriptId":"u9"},
    "687c9df62f1e478caf45e7b111968ad2":{
      "scriptId":"u10"},
    "4385970d609e43319ac9faa0d684e64d":{
      "scriptId":"u11"},
    "cc5f82157a8c450880cbcbbae8638432":{
      "scriptId":"u12"},
    "df97320436f24daaaf402aa46a3e65d4":{
      "scriptId":"u13"},
    "e8f35e7cd1e64fa7a0da95b3313e05b8":{
      "scriptId":"u14"},
    "8e7919945b4f485ead0923cdbbe4561f":{
      "scriptId":"u15"},
    "fcf2a8759c7941c3bc98bddb02d0d7a8":{
      "scriptId":"u16"},
    "bb751a39178141b9a28fed9a8e117427":{
      "scriptId":"u17"},
    "a8d8f4520ea74206b0bac8cb91fb49b0":{
      "scriptId":"u18"}}});