$axure.loadCurrentPage({
  "url":"修改个人信息.html",
  "generationDate":new Date(1527858167282.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"78d8bc6ae83e4594a307d347d56b9b91",
    "type":"Axure:Page",
    "name":"修改个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"897e99bd13a64426849601d8e8a6a6b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":33,
              "y":-83},
            "size":{
              "width":268,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b73a226658a840d29b6eac65d88adf1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":33,
                  "y":-83},
                "size":{
                  "width":268,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0fb98f82e8f45e0ba79fd054f223797",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":681,
              "y":-57},
            "size":{
              "width":184,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8bd65eb2af1429584d2a7f3fc1190f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":681,
                  "y":-57},
                "size":{
                  "width":184,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6f62aee6cda4dc19ac7324c9e7e99ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":871,
              "y":-57},
            "size":{
              "width":80,
              "height":23},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2b15b5c2265467bb99ba41aa6974695",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":871,
                  "y":-57},
                "size":{
                  "width":80,
                  "height":23},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"6f8a8069e9ac42338f58dfbb4d79a3c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.1",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "textShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}},
            "location":{
              "x":49,
              "y":10},
            "size":{
              "width":1191,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26ceecb5e0fd4c448db7de804584dade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.1",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "textShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}},
                "location":{
                  "x":49,
                  "y":10},
                "size":{
                  "width":1191,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"e0d853541a7a4666ba53ce6adbde8d05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":113,
              "y":47},
            "size":{
              "width":28,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c18540069da4e41964fb922d7134b23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":47},
                "size":{
                  "width":28,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae491510f75246eeb2673d43d3f55578",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":47},
            "size":{
              "width":268,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95f4d81c3f64488b8b617b3a3a807013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":47},
                "size":{
                  "width":268,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"843fd866cf634fdfa1dc81981b4e1807",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":790,
              "y":73},
            "size":{
              "width":184,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79295b591c6a4f8d81d5979c8f07106f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":790,
                  "y":73},
                "size":{
                  "width":184,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efacd07adb5543e5912720810b45bc93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":980,
              "y":73},
            "size":{
              "width":80,
              "height":23},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e22d8ea5e94a4c990ea541834321f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":980,
                  "y":73},
                "size":{
                  "width":80,
                  "height":23},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"8a078fa06c094fae9252ea3644fb3b5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":118},
            "size":{
              "width":957,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1d1878941974e81a29198a347df35b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":118},
                "size":{
                  "width":957,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.png"}},
{
          "id":"73f04099b8ff480b85c9ada8e26209c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":920,
              "y":128},
            "size":{
              "width":80,
              "height":23},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2c0f13207f40cd8d88f3b7a213c3ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":920,
                  "y":128},
                "size":{
                  "width":80,
                  "height":23},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"ee7aee137d7d4802ba7dd5da11cad6bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":121},
            "size":{
              "width":39,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34c2a8afa664457ca52f5467fd9f01ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":121},
                "size":{
                  "width":39,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"b2f4338940d1427188b79d0fec9cd8ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":462,
              "y":127},
            "size":{
              "width":258,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ee854ce15e4d6799f7cb1497f19aed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":462,
                  "y":127},
                "size":{
                  "width":258,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf3ed2b7eb66472792b31a2102d2c0cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "lineSpacing":"48px",
            "location":{
              "x":320,
              "y":280},
            "size":{
              "width":650,
              "height":417}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"812aea63af9e44748b4e2c337aa6eb0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "lineSpacing":"48px",
                "location":{
                  "x":320,
                  "y":280},
                "size":{
                  "width":650,
                  "height":417}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cd33449ff8e465ead32bcc020737b43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":700,
              "y":620},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73ff839830644ce8ab2160f8770209f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":700,
                  "y":620},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改个人信息/u26.png"}},
{
          "id":"0c48eb111afd43df85ac08bcd8c29d58",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":560,
              "y":697},
            "size":{
              "width":110,
              "height":33}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"查看个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "897e99bd13a64426849601d8e8a6a6b8":{
      "scriptId":"u0"},
    "b73a226658a840d29b6eac65d88adf1e":{
      "scriptId":"u1"},
    "c0fb98f82e8f45e0ba79fd054f223797":{
      "scriptId":"u2"},
    "f8bd65eb2af1429584d2a7f3fc1190f3":{
      "scriptId":"u3"},
    "f6f62aee6cda4dc19ac7324c9e7e99ed":{
      "scriptId":"u4"},
    "b2b15b5c2265467bb99ba41aa6974695":{
      "scriptId":"u5"},
    "6f8a8069e9ac42338f58dfbb4d79a3c2":{
      "scriptId":"u6"},
    "26ceecb5e0fd4c448db7de804584dade":{
      "scriptId":"u7"},
    "e0d853541a7a4666ba53ce6adbde8d05":{
      "scriptId":"u8"},
    "8c18540069da4e41964fb922d7134b23":{
      "scriptId":"u9"},
    "ae491510f75246eeb2673d43d3f55578":{
      "scriptId":"u10"},
    "95f4d81c3f64488b8b617b3a3a807013":{
      "scriptId":"u11"},
    "843fd866cf634fdfa1dc81981b4e1807":{
      "scriptId":"u12"},
    "79295b591c6a4f8d81d5979c8f07106f":{
      "scriptId":"u13"},
    "efacd07adb5543e5912720810b45bc93":{
      "scriptId":"u14"},
    "e0e22d8ea5e94a4c990ea541834321f0":{
      "scriptId":"u15"},
    "8a078fa06c094fae9252ea3644fb3b5d":{
      "scriptId":"u16"},
    "f1d1878941974e81a29198a347df35b7":{
      "scriptId":"u17"},
    "73f04099b8ff480b85c9ada8e26209c4":{
      "scriptId":"u18"},
    "5c2c0f13207f40cd8d88f3b7a213c3ad":{
      "scriptId":"u19"},
    "ee7aee137d7d4802ba7dd5da11cad6bd":{
      "scriptId":"u20"},
    "34c2a8afa664457ca52f5467fd9f01ca":{
      "scriptId":"u21"},
    "b2f4338940d1427188b79d0fec9cd8ef":{
      "scriptId":"u22"},
    "20ee854ce15e4d6799f7cb1497f19aed":{
      "scriptId":"u23"},
    "cf3ed2b7eb66472792b31a2102d2c0cd":{
      "scriptId":"u24"},
    "812aea63af9e44748b4e2c337aa6eb0e":{
      "scriptId":"u25"},
    "7cd33449ff8e465ead32bcc020737b43":{
      "scriptId":"u26"},
    "73ff839830644ce8ab2160f8770209f2":{
      "scriptId":"u27"},
    "0c48eb111afd43df85ac08bcd8c29d58":{
      "scriptId":"u28"}}});