
@startuml
title 基于GitHub的实验管理平台--学生列表用例的顺序图
actor users
users->students:用户以学生的类型登录
students->terms:学生选择相应的学期
terms->disciplines:选择该学期所对应的的课程
disciplines->grades
grades->experiments
alt 如果users是老师
	students -> grades
	grades -> experiments
	experiments --> users:每个学生的信息、及每个实验的成绩以及每个实验的具体评分项
end

@enduml