$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1527858166055.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c22e56bef8184e6aad5807cb638e1a07",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b01a5c939f314318aba5f5b8c74d844d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.1",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "textShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}},
            "location":{
              "x":40,
              "y":10},
            "size":{
              "width":1191,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ada1c2d1c04740c994743909b2f7e0ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.1",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "textShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}},
                "location":{
                  "x":40,
                  "y":10},
                "size":{
                  "width":1191,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"b7ad41de701940709cd050f0f458b3de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":113,
              "y":47},
            "size":{
              "width":28,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e8fcb6bf51e4d5dbbf74816fbc812d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":47},
                "size":{
                  "width":28,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a24588ea8413463a927d47c7267be81a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":47},
            "size":{
              "width":268,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b1ae9ebc424b68818cb532b13e3306",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":47},
                "size":{
                  "width":268,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee86a0d049804ae08444ada997ea6f07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":450,
              "y":230},
            "size":{
              "width":340,
              "height":66},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18f38fe5eeda459cb5a8f81def51217d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":450,
                  "y":230},
                "size":{
                  "width":340,
                  "height":66},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"212ce6431e9b4791a97d4460566d02dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":241},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57b357d3b3bc4a1887456c3aea4f0c44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":241},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u8.png"}},
{
          "id":"d56ea78e2e364d6c8327df9a5dbbed44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":450,
              "y":354},
            "size":{
              "width":340,
              "height":66},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"784963b406574d88a5afdf87215e0d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":450,
                  "y":354},
                "size":{
                  "width":340,
                  "height":66},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"16c0b8f6649f4b2d9b9f208bc43c9bfd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":370},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3bac853cf634ddbbfae9a1f2bfa07d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":370},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"a53c8ca76f794c5da0eb021aace0fefb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":450,
              "y":464},
            "size":{
              "width":340,
              "height":66},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1333f42c5b44f5dad81d993de93b670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":450,
                  "y":464},
                "size":{
                  "width":340,
                  "height":66},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"00d25b0eed60439ba4b4ffd4eeec0764",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":474,
              "y":555},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2d8f9e1c9444202a4403ef697e92759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":474,
                  "y":555},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"23cc3381d77447bcb9b9e06a889f6bfa",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":604,
              "y":555},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8c744cf89244a3faae3c019f2003414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":604,
                  "y":555},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"3358806c43af444cb190044aa071c2ab",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":720,
              "y":555},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66e274fe5d174c86960ae5fd17fbcad7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":720,
                  "y":555},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"e0a570286ba148489b13ba674b687afa",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":460,
              "y":600},
            "size":{
              "width":108,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1e9996408b24fe582bd8fd07979c645",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":460,
                  "y":600},
                "size":{
                  "width":108,
                  "height":26}},
              "adaptiveStyles":{
}}]},
{
          "id":"dea2de44c5e347b79c6fdbc9bc6155e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":700,
              "y":600},
            "size":{
              "width":90,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1270c8ed9796479cba5365c84d2c58d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":700,
                  "y":600},
                "size":{
                  "width":90,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b01a5c939f314318aba5f5b8c74d844d":{
      "scriptId":"u0"},
    "ada1c2d1c04740c994743909b2f7e0ba":{
      "scriptId":"u1"},
    "b7ad41de701940709cd050f0f458b3de":{
      "scriptId":"u2"},
    "9e8fcb6bf51e4d5dbbf74816fbc812d8":{
      "scriptId":"u3"},
    "a24588ea8413463a927d47c7267be81a":{
      "scriptId":"u4"},
    "86b1ae9ebc424b68818cb532b13e3306":{
      "scriptId":"u5"},
    "ee86a0d049804ae08444ada997ea6f07":{
      "scriptId":"u6"},
    "18f38fe5eeda459cb5a8f81def51217d":{
      "scriptId":"u7"},
    "212ce6431e9b4791a97d4460566d02dd":{
      "scriptId":"u8"},
    "57b357d3b3bc4a1887456c3aea4f0c44":{
      "scriptId":"u9"},
    "d56ea78e2e364d6c8327df9a5dbbed44":{
      "scriptId":"u10"},
    "784963b406574d88a5afdf87215e0d97":{
      "scriptId":"u11"},
    "16c0b8f6649f4b2d9b9f208bc43c9bfd":{
      "scriptId":"u12"},
    "e3bac853cf634ddbbfae9a1f2bfa07d8":{
      "scriptId":"u13"},
    "a53c8ca76f794c5da0eb021aace0fefb":{
      "scriptId":"u14"},
    "e1333f42c5b44f5dad81d993de93b670":{
      "scriptId":"u15"},
    "00d25b0eed60439ba4b4ffd4eeec0764":{
      "scriptId":"u16"},
    "c2d8f9e1c9444202a4403ef697e92759":{
      "scriptId":"u17"},
    "23cc3381d77447bcb9b9e06a889f6bfa":{
      "scriptId":"u18"},
    "d8c744cf89244a3faae3c019f2003414":{
      "scriptId":"u19"},
    "3358806c43af444cb190044aa071c2ab":{
      "scriptId":"u20"},
    "66e274fe5d174c86960ae5fd17fbcad7":{
      "scriptId":"u21"},
    "e0a570286ba148489b13ba674b687afa":{
      "scriptId":"u22"},
    "f1e9996408b24fe582bd8fd07979c645":{
      "scriptId":"u23"},
    "dea2de44c5e347b79c6fdbc9bc6155e1":{
      "scriptId":"u24"},
    "1270c8ed9796479cba5365c84d2c58d4":{
      "scriptId":"u25"}}});