$axure.loadCurrentPage({
  "url":"修改密码.html",
  "generationDate":new Date(1527858167376.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d17748cdf9de4927b00a912dd0ef6738",
    "type":"Axure:Page",
    "name":"修改密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9d1e52773fa9492fa737f6f7ca97e0f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.1",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "textShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}},
            "location":{
              "x":60,
              "y":10},
            "size":{
              "width":1191,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dfc113102e2402ba2d7492e0cf632e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.1",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "textShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}},
                "location":{
                  "x":60,
                  "y":10},
                "size":{
                  "width":1191,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"9f75d8b1bcfa42919fdfad6f02cec696",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":113,
              "y":47},
            "size":{
              "width":28,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af3873788d8548a2bb31750b267f1388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":47},
                "size":{
                  "width":28,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f9fcf491ad2433483a1cedb1bfde8a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":47},
            "size":{
              "width":268,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ca18a1e4d6e4a52a2005646e02e937b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":47},
                "size":{
                  "width":268,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3633f2173674137b66f899b6a87b4c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":790,
              "y":73},
            "size":{
              "width":184,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e8b967956e14679af9e56218e5851bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":790,
                  "y":73},
                "size":{
                  "width":184,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"087430adc35742c595cdb80e87bf6cfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":980,
              "y":73},
            "size":{
              "width":80,
              "height":23},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8a672ee5c4a4aa48197f949b37c838a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":980,
                  "y":73},
                "size":{
                  "width":80,
                  "height":23},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"17ccf5e4af8f424d9a88247d94c87ffc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":118},
            "size":{
              "width":957,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74ece38c4cae4d19af444e02c7e173aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":118},
                "size":{
                  "width":957,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.png"}},
{
          "id":"94f18b35a27f4f0a8dfb5eb855805e22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":920,
              "y":128},
            "size":{
              "width":80,
              "height":23},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3383f26c6807485fad7f5d4abe5e0fda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":920,
                  "y":128},
                "size":{
                  "width":80,
                  "height":23},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"dbe99dde417243df82f998da14b89f2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":121},
            "size":{
              "width":39,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a461616241542c59d21cf387622e492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":121},
                "size":{
                  "width":39,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"a552d76aed2e4bd78cb7e268700c92af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":462,
              "y":127},
            "size":{
              "width":258,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5c10f6706ef421183c00b358653e2ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":462,
                  "y":127},
                "size":{
                  "width":258,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"881cddabd7734a9cbb0f2737557ae3e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":421.5,
              "y":264},
            "size":{
              "width":340,
              "height":66},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95b9f47a2b324a65b1ccd59c9dbcbdaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":421.5,
                  "y":264},
                "size":{
                  "width":340,
                  "height":66},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"5d3b8999b40b4b1eaf26d5525b228ea4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":422,
              "y":375},
            "size":{
              "width":340,
              "height":66},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60db1c5aabd84cebbc12cc8177a26eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":422,
                  "y":375},
                "size":{
                  "width":340,
                  "height":66},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"b93a498c615f44fcb213392520e3e604",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":422,
              "y":490},
            "size":{
              "width":340,
              "height":66},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"966d21be16c44b238db20596b3846c13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":422,
                  "y":490},
                "size":{
                  "width":340,
                  "height":66},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"ee3f4a658a9c490e8366d28c106f5774",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":422,
              "y":600},
            "size":{
              "width":340,
              "height":66},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf4f8cf4a1114255aa6f6d7daa481c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":422,
                  "y":600},
                "size":{
                  "width":340,
                  "height":66},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改密码/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9d1e52773fa9492fa737f6f7ca97e0f0":{
      "scriptId":"u0"},
    "8dfc113102e2402ba2d7492e0cf632e2":{
      "scriptId":"u1"},
    "9f75d8b1bcfa42919fdfad6f02cec696":{
      "scriptId":"u2"},
    "af3873788d8548a2bb31750b267f1388":{
      "scriptId":"u3"},
    "2f9fcf491ad2433483a1cedb1bfde8a5":{
      "scriptId":"u4"},
    "1ca18a1e4d6e4a52a2005646e02e937b":{
      "scriptId":"u5"},
    "a3633f2173674137b66f899b6a87b4c5":{
      "scriptId":"u6"},
    "5e8b967956e14679af9e56218e5851bf":{
      "scriptId":"u7"},
    "087430adc35742c595cdb80e87bf6cfc":{
      "scriptId":"u8"},
    "f8a672ee5c4a4aa48197f949b37c838a":{
      "scriptId":"u9"},
    "17ccf5e4af8f424d9a88247d94c87ffc":{
      "scriptId":"u10"},
    "74ece38c4cae4d19af444e02c7e173aa":{
      "scriptId":"u11"},
    "94f18b35a27f4f0a8dfb5eb855805e22":{
      "scriptId":"u12"},
    "3383f26c6807485fad7f5d4abe5e0fda":{
      "scriptId":"u13"},
    "dbe99dde417243df82f998da14b89f2f":{
      "scriptId":"u14"},
    "1a461616241542c59d21cf387622e492":{
      "scriptId":"u15"},
    "a552d76aed2e4bd78cb7e268700c92af":{
      "scriptId":"u16"},
    "e5c10f6706ef421183c00b358653e2ab":{
      "scriptId":"u17"},
    "881cddabd7734a9cbb0f2737557ae3e2":{
      "scriptId":"u18"},
    "95b9f47a2b324a65b1ccd59c9dbcbdaa":{
      "scriptId":"u19"},
    "5d3b8999b40b4b1eaf26d5525b228ea4":{
      "scriptId":"u20"},
    "60db1c5aabd84cebbc12cc8177a26eb4":{
      "scriptId":"u21"},
    "b93a498c615f44fcb213392520e3e604":{
      "scriptId":"u22"},
    "966d21be16c44b238db20596b3846c13":{
      "scriptId":"u23"},
    "ee3f4a658a9c490e8366d28c106f5774":{
      "scriptId":"u24"},
    "bf4f8cf4a1114255aa6f6d7daa481c11":{
      "scriptId":"u25"}}});