$axure.loadCurrentPage({
  "url":"查看个人信息.html",
  "generationDate":new Date(1527858167206.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0149f01375994bcb9f6f227d4ffacefd",
    "type":"Axure:Page",
    "name":"查看个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5169924127df40e6a10e258d5a94db0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.1",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "textShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}},
            "location":{
              "x":49,
              "y":10},
            "size":{
              "width":1191,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a99bae7303a04f1a8e38374c5e0fab14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.1",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "textShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}},
                "location":{
                  "x":49,
                  "y":10},
                "size":{
                  "width":1191,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"251ec7635c224915806864ec7ddce207",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":113,
              "y":47},
            "size":{
              "width":28,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42e9281971194ccf9e7240d382b9a775",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":113,
                  "y":47},
                "size":{
                  "width":28,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18bb3eab24014ba0ba1be10b2e6842b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":47},
            "size":{
              "width":268,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"027a5424514c4e1386bd5782a714ea87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":47},
                "size":{
                  "width":268,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78bb5faa78c744cbb70d7fc831ef873d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":790,
              "y":73},
            "size":{
              "width":184,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14306f39945d4180995f0e690f798e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":790,
                  "y":73},
                "size":{
                  "width":184,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fbb910e84c84719804015bdcb93d358",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":980,
              "y":73},
            "size":{
              "width":80,
              "height":23},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66177a504e63438c941421cb41e4ddc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":980,
                  "y":73},
                "size":{
                  "width":80,
                  "height":23},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"a4bc15614e9c4496a4a060c1327c63c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":118},
            "size":{
              "width":957,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca933eb87f9d490f9c88ff29523da1ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":118},
                "size":{
                  "width":957,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.png"}},
{
          "id":"7151e66f38744d4a898179f2f9f75498",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE6FAFA},
            "location":{
              "x":920,
              "y":128},
            "size":{
              "width":80,
              "height":23},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"398d510516e346f1bea7bd00703d6632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6FAFA},
                "location":{
                  "x":920,
                  "y":128},
                "size":{
                  "width":80,
                  "height":23},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"23b9f13723a74c88b0aed231b7d7da4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":121},
            "size":{
              "width":39,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2571039f3f134da2bd321c0ff1f391e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":121},
                "size":{
                  "width":39,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"ad976dcb663f41b9be5ca60004d5428a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":462,
              "y":127},
            "size":{
              "width":258,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f929a2ae4f941f2aa2f1b0be28f35e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":462,
                  "y":127},
                "size":{
                  "width":258,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07d3aa319aa843d7a5fe891a3a81cbaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "lineSpacing":"48px",
            "location":{
              "x":320,
              "y":280},
            "size":{
              "width":700,
              "height":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07d306fc4bb14e61b48a6d65bbff0b89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "lineSpacing":"48px",
                "location":{
                  "x":320,
                  "y":280},
                "size":{
                  "width":700,
                  "height":440}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5169924127df40e6a10e258d5a94db0a":{
      "scriptId":"u0"},
    "a99bae7303a04f1a8e38374c5e0fab14":{
      "scriptId":"u1"},
    "251ec7635c224915806864ec7ddce207":{
      "scriptId":"u2"},
    "42e9281971194ccf9e7240d382b9a775":{
      "scriptId":"u3"},
    "18bb3eab24014ba0ba1be10b2e6842b8":{
      "scriptId":"u4"},
    "027a5424514c4e1386bd5782a714ea87":{
      "scriptId":"u5"},
    "78bb5faa78c744cbb70d7fc831ef873d":{
      "scriptId":"u6"},
    "14306f39945d4180995f0e690f798e91":{
      "scriptId":"u7"},
    "1fbb910e84c84719804015bdcb93d358":{
      "scriptId":"u8"},
    "66177a504e63438c941421cb41e4ddc1":{
      "scriptId":"u9"},
    "a4bc15614e9c4496a4a060c1327c63c8":{
      "scriptId":"u10"},
    "ca933eb87f9d490f9c88ff29523da1ec":{
      "scriptId":"u11"},
    "7151e66f38744d4a898179f2f9f75498":{
      "scriptId":"u12"},
    "398d510516e346f1bea7bd00703d6632":{
      "scriptId":"u13"},
    "23b9f13723a74c88b0aed231b7d7da4b":{
      "scriptId":"u14"},
    "2571039f3f134da2bd321c0ff1f391e5":{
      "scriptId":"u15"},
    "ad976dcb663f41b9be5ca60004d5428a":{
      "scriptId":"u16"},
    "7f929a2ae4f941f2aa2f1b0be28f35e4":{
      "scriptId":"u17"},
    "07d3aa319aa843d7a5fe891a3a81cbaf":{
      "scriptId":"u18"},
    "07d306fc4bb14e61b48a6d65bbff0b89":{
      "scriptId":"u19"}}});